experiments:

  - model: ConvNeXtLarge
    save_path: "convnextlarge_metrics_all_convnext.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: True
      num_samples: null
      test_size: 0.2

  - model: ConvNeXtBase
    save_path: "convnextbase_metrics_all_convnext.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: True
      num_samples: null
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_metrics_all_convnext.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: True
      num_samples: null
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_metrics_all_convnext.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: True
      num_samples: null
      test_size: 0.2