experiments:
  - model: ResNet101
    save_path: "results/resnet101_metrics_all_models_2.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: null
      test_size: 0.2

  - model: ResNet50
    save_path: "results/resnet50_metrics_all_models_2.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: null
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "results/convnexttiny_metrics_all_models_2.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: null
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "results/convnextsmall_metrics_all_models_2.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: null
      test_size: 0.2