experiments:
  - model: ConvNeXtTiny
    save_path: "convnexttiny_metrics_all_convnext.csv"
    hyperparameters:
      num_epochs: 30
      lr: 0.0008
      warmup_steps: 300
      weight_decay: 0.1
      batch_size: 128
      decay: "linear"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_metrics_all_convnext.csv"
    hyperparameters:
      num_epochs: 30
      lr: 0.0006
      warmup_steps: 300
      weight_decay: 0.1
      batch_size: 128
      decay: "linear"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2

  - model: ConvNeXtXL
    save_path: "convnextxl_metrics_all_convnext.csv"
    hyperparameters:
      num_epochs: 30
      lr: 0.0004
      warmup_steps: 300
      weight_decay: 0.1
      batch_size: 128
      decay: "linear"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2