experiments:
  - model: ResNet50
    save_path: "resnet50_metrics_vit_test.csv"
    hyperparameters:
      num_epochs: 50
      lr: 0.0008
      warmup_steps: 400
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: true
      num_samples: null
      test_size: 0.2