experiments:
  - model: ConvNeXtTiny
    save_path: "convnexttiny_2000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 2000
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_4000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 4000
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_6000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 6000
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_8000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 8000
      test_size: 0.2
  - model: ConvNeXtTiny
    save_path: "convnexttiny_10000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 10000
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_12000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 12000
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_14000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 14000
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_16000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 16000
      test_size: 0.2

  - model: ConvNeXtTiny
    save_path: "convnexttiny_18000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 18000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_2000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 2000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_4000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 4000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_6000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 6000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_8000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 8000
      test_size: 0.2
  - model: ConvNeXtSmall
    save_path: "convnextsmall_10000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 10000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_12000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 12000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_14000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 14000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_16000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 16000
      test_size: 0.2

  - model: ConvNeXtSmall
    save_path: "convnextsmall_18000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: False
      num_samples: 18000
      test_size: 0.2