experiments:
  - model: ConvNeXtSmall
    save_path: "convnextsmall_group_dataaugmentation_test.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: False
      vflip: False
      rotate: False
      group: True
      num_samples: null
      test_size: 0.2