experiments:
  # ViT_S16 diff num datapoints
  - model: ViT_S16
    save_path: "vit_s16_2000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 2000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_4000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 4000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_6000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 6000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_8000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 8000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_10000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 10000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_12000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 12000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_14000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 14000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_16000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 16000
      test_size: 0.2
  - model: ViT_S16
    save_path: "vit_s16_18000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 18000
      test_size: 0.2
  # ViT_T16 diff num datapoints
  - model: ViT_T16
    save_path: "vit_t16_2000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 2000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_4000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 4000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_6000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 6000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_8000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 8000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_10000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 10000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_12000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 12000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_14000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 14000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_16000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 16000
      test_size: 0.2
  - model: ViT_T16
    save_path: "vit_t16_18000_metrics_diff_num_datapoints.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: 18000
      test_size: 0.2
