experiments:
  - model: ViT_B4
    save_path: "ViT_B4_metrics_vit_patch_size.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: true
      num_samples: null
      test_size: 0.2

  - model: ViT_B8
    save_path: "ViT_B8_metrics_vit_patch_size.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: true
      num_samples: null
      test_size: 0.2

  - model: ViT_B16
    save_path: "ViT_B16_metrics_vit_patch_size.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      use_hv_flip: true
      num_samples: null
      test_size: 0.2