experiments:
  - model: ResNet50
    save_path: "resnet50_metrics_vit_test.csv"
    hyperparameters:
      num_epochs: 30
      lr: 0.0008
      warmup_steps: 300
      weight_decay: 0.1
      batch_size: 128
      decay: "linear"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2

  - model: ResNet101
    save_path: "resnet101_metrics_vit_test.csv"
    hyperparameters:
      num_epochs: 30
      lr: 0.0008
      warmup_steps: 300
      weight_decay: 0.1
      batch_size: 128
      decay: "linear"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2

  - model: ResNet152
    save_path: "resnet152_metrics_vit_test.csv"
    hyperparameters:
      num_epochs: 30
      lr: 0.0008
      warmup_steps: 300
      weight_decay: 0.1
      batch_size: 128
      decay: "linear"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2