experiments:
  - model: ViT_B16
    save_path: "vit_b16_metrics_vit_test_3.csv"
    hyperparameters:
      num_epochs: 30
      lr: 0.0008
      warmup_steps: 300
      weight_decay: 0.1
      batch_size: 128
      decay: "linear"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2