experiments:
  - model: ViT_B16
    save_path: "vit_b16_metrics_vit_test_2.csv"
    hyperparameters:
      num_epochs: 20
      lr: 0.0008
      warmup_steps: 220
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      normalize: false
      num_samples: null
      test_size: 0.2