experiments:
  - model: ViT_S8
    save_path: "vit_s8_metrics_more_vits.csv"
    hyperparameters:
      num_epochs: 100
      lr: 0.00025
      warmup_steps: 4000
      weight_decay: 0.05
      batch_size: 32
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: False
      num_samples: null
      test_size: 0.2