experiments:
  - model: ViT_S16
    save_path: "vit_s16_extralong_v2.csv"
    hyperparameters:
      num_epochs: 500
      lr: 0.0008
      warmup_steps: 1000
      weight_decay: 0.1
      batch_size: 128
      decay: "cosine"
    data:
      hflip: True
      vflip: True
      rotate: True
      group: True
      num_samples: null
      test_size: 0.2
